### ISSUE TITLE
Unable to start application

### ISSUE THREAD

**Issue by pnpninja** [kivanov82/DutchBlockchainHackathon#1]
I see an error during startup - 

`Application startup failed
java.lang.IllegalStateException: Cannot load configuration class: nl.hackathon.security.SecurityConfiguration
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:416)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:263)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:284)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:130)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:681)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at nl.hackathon.FoundationApplication.main(FoundationApplication.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:483)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Unable to load cache item
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:79)
	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:480)
	at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:337)
	at org.springframework.context.annotation.ConfigurationClassEnhancer.createClass(ConfigurationClassEnhancer.java:135)
	at org.springframework.context.annotation.ConfigurationClassEnhancer.enhance(ConfigurationClassEnhancer.java:107)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:406)
	... 17 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/web/accept/ContentNegotiationStrategy
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getDeclaredConstructors(Class.java:2020)
	at org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:566)
	at org.springframework.cglib.transform.TransformingClassGenerator.generateClass(TransformingClassGenerator.java:33)
	at org.springframework.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanFactoryAwareGeneratorStrategy.generate(ConfigurationClassEnhancer.java:249)
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329)
	at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:492)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	... 25 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.web.accept.ContentNegotiationStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 common frames omitted
`

How do I fix this?

**Comment by bootv2** [comment]
Hello Prateek,

Due to issues within the team this project has been discontinued. I am
unable to help you.
Nevertheless you have my permission to use this code in any way you'd like.

Regards,
Tim Boode

On Feb 12, 2018 7:05 PM, "Prateek Narendra" <notifications@github.com>
wrote:

I see an error during startup -

Application startup failed java.lang.IllegalStateException: Cannot load
configuration class: nl.hackathon.security.SecurityConfiguration at
org.springframework.context.annotation.ConfigurationClassPostProcesso
r.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:416) at
org.springframework.context.annotation.ConfigurationClassPostProcesso
r.postProcessBeanFactory(ConfigurationClassPostProcessor.java:263) at
org.springframework.context.support.PostProcessorRegistrationDelegate.
invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:284)
at org.springframework.context.support.PostProcessorRegistrationDelegate.
invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:130)
at org.springframework.context.support.AbstractApplicationContext.
invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:681) at
org.springframework.context.support.AbstractApplicationContext.refresh(
AbstractApplicationContext.java:523) at org.springframework.boot.
SpringApplication.refresh(SpringApplication.java:759) at
org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
at nl.hackathon.FoundationApplication.main(FoundationApplication.java:12)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(
DelegatingMethodAccessorImpl.java:43) at
java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:483)
at java.lang.Thread.run(Thread.java:745) Caused by:
java.lang.IllegalStateException:
Unable to load cache item at org.springframework.cglib.
core.internal.LoadingCache.createEntry(LoadingCache.java:79) at
org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
at org.springframework.cglib.core.AbstractClassGenerator$
ClassLoaderData.get(AbstractClassGenerator.java:116) at
org.springframework.cglib.core.AbstractClassGenerator.
create(AbstractClassGenerator.java:291) at org.springframework.cglib.
proxy.Enhancer.createHelper(Enhancer.java:480) at org.springframework.cglib.
proxy.Enhancer.createClass(Enhancer.java:337) at
org.springframework.context.annotation.ConfigurationClassEnhancer.
createClass(ConfigurationClassEnhancer.java:135) at
org.springframework.context.annotation.ConfigurationClassEnhancer.enhance(
ConfigurationClassEnhancer.java:107) at org.springframework.context.
annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(
ConfigurationClassPostProcessor.java:406) ... 17 common frames omitted
Caused by: java.lang.NoClassDefFoundError:
org/springframework/web/accept/ContentNegotiationStrategy
at java.lang.Class.getDeclaredConstructors0(Native Method) at
java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) at
java.lang.Class.getDeclaredConstructors(Class.java:2020) at
org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:566)
at org.springframework.cglib.transform.TransformingClassGenerator.
generateClass(TransformingClassGenerator.java:33) at
org.springframework.cglib.core.DefaultGeneratorStrategy.generate(
DefaultGeneratorStrategy.java:25) at org.springframework.context.annotation.
ConfigurationClassEnhancer$BeanFactoryAwareGeneratorStrategy.generate(
ConfigurationClassEnhancer.java:249) at org.springframework.cglib.
core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329) at
org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:492) at
org.springframework.cglib.core.AbstractClassGenerator$
ClassLoaderData$3.apply(AbstractClassGenerator.java:93) at
org.springframework.cglib.core.AbstractClassGenerator$
ClassLoaderData$3.apply(AbstractClassGenerator.java:91) at
org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
at java.util.concurrent.FutureTask.run(FutureTask.java:266) at
org.springframework.cglib.core.internal.LoadingCache.
createEntry(LoadingCache.java:61) ... 25 common frames omitted Caused by:
java.lang.ClassNotFoundException:
org.springframework.web.accept.ContentNegotiationStrategy
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) at
java.lang.ClassLoader.loadClass(ClassLoader.java:424) at
java.lang.ClassLoader.loadClass(ClassLoader.java:357) ... 39 common frames
omitted

How do I fix this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kivanov82/DutchBlockchainHackathon/issues/1>, or mute
the thread
